export const FORM_STATUS_CODE = {
    FORM_DEFAULT: "FORM_DEFAULT",
    FORM_UPDATE_SUCCESS: "FORM_UPDATE_SUCCESS",

    INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
    INVALID_INPUT: "INVALID_INPUT",
    NICKNAME_TOO_SHORT: "NICKNAME_TOO_SHORT",

    PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
    INVALID_PASSWORD_FORMAT: "INVALID_PASSWORD_FORMAT",
    WORNG_VALIDATION_CODE: "WORNG_VALIDATION_CODE",

    WORNG_PASSWORD: "WORNG_PASSWORD",
    REPASSWORD_NOT_MATCHED: "REPASSWORD_NOT_MATCHED",
    SERVER_UNAUTHORIZED: "SERVER_UNAUTHORIZED",
    SEVER_ERROR: "SEVER_ERROR",
}


const FORM_STATUS_MESSAGE_KOR = {
    FORM_DEFAULT: "",
    FORM_UPDATE_SUCCESS: "업데이트 되었습니다.",

    INVALID_EMAIL_FORMAT: "올바르지 않은 Email 형식입니다.",
    INVALID_INPUT: "올바르지 않은 입력값입니다.",
    NICKNAME_TOO_SHORT: "nickname은 3자리 이상이어야 합니다.",

    PASSWORD_TOO_SHORT: "패스워드는 8자 이상이어야 합니다.",
    INVALID_PASSWORD_FORMAT: "올바르지 않은 패스워드 형식입니다.",
    WORNG_VALIDATION_CODE: "올바르지않은 인증코드입니다.",

    WORNG_PASSWORD: "잘못된 비밀번호입니다.",
    REPASSWORD_NOT_MATCHED: "비밀번호 확인값이 일치하지 않습니다.",
    SERVER_UNAUTHORIZED: "허용되지 않은 접근입니다.",
    SERVER_ERROR: "옳바르지 않은 접근이거나 잘못된 값을 입력 했습했니다.",
}


export const FORM_STATUS_MESSAGE = FORM_STATUS_MESSAGE_KOR;
